export const AudiovisualData = [
    {
        id: 'Audio1',
        subTitles: 'Parque de diversiones Santander',
        title: 'Unboxing',
        imgSrc: 'https://www.ludics.cl/demoweb/img/servicios/Audiovisual/1- PARQUE DE DIVERSIONES (Parque de diversiones Santander - Unboxing)_1_11zon.webp',
        videoSrc: 'https://www.ludics.cl/demoweb/img/servicios/Audiovisual/video/1-unboxing-parque-diversiones.mp4',
        videoUrl: 'https://www.youtube.com/watch?v=foZ-F7WjxSM',
    },
    {
        id: 'Audio2',
        subTitles: 'AFP modelo',
        title: 'Spot Corporativo',
        imgSrc: 'https://www.ludics.cl/demoweb/img/servicios/Audiovisual/2- AFP MODELO (Spot Corporativo - AFP modelo)_2_11zon.webp',
        videoSrc: 'https://www.ludics.cl/demoweb/img/servicios/Audiovisual/video/2-afp-modelo1.mp4',
        videoUrl: 'https://www.youtube.com/watch?v=8vBZFuCfDdg',
    },
    {
        id: 'Audio3',
        subTitles: 'P&G',
        title: 'Infográfico',
        imgSrc: 'https://www.ludics.cl/demoweb/img/servicios/Audiovisual/3- P&G (Infográfico - P&G)_3.webp',
        videoSrc: 'https://www.ludics.cl/demoweb/img/servicios/Audiovisual/video/3-pyg.mp4',
        videoUrl: 'https://www.youtube.com/watch?v=aalV7eLg6oc',
    },
    {
        id: 'Audio4',
        subTitles: 'Campaña deciochera',
        title: 'Unboxing',
        imgSrc: 'https://www.ludics.cl/demoweb/img/servicios/Audiovisual/4- 18 SEP (Campaña deciochera - Unboxing)_4.webp',
        videoSrc: 'https://www.ludics.cl/demoweb/img/servicios/Audiovisual/video/4-unboxing-18ro.mp4',
        videoUrl: 'https://www.youtube.com/watch?v=Aw8uckZHfX8',
    },
    {
        id: 'Audio5',
        subTitles: 'Campaña fin de año',
        title: 'Unboxing',
        imgSrc: 'https://www.ludics.cl/demoweb/img/servicios/Audiovisual/5- Playero (Campaña fin de año - Unboxing)_5.webp',
        videoSrc: 'https://www.ludics.cl/demoweb/img/servicios/Audiovisual/video/5-unboxing-player1.mp4',
        videoUrl: 'https://www.youtube.com/watch?v=u1nQLzkKLJM',
    },
    {
        id: 'Audio6',
        subTitles: 'Santander',
        title: 'Campañas internas',
        imgSrc: 'https://www.ludics.cl/demoweb/img/servicios/Audiovisual/6- Team Santander (Campañas - Team Santander)_6.webp',
        videoSrc: 'https://www.ludics.cl/demoweb/img/servicios/Audiovisual/video/6-TEAMS-SANTANDER.mp4',
        videoUrl: 'https://www.youtube.com/watch?v=hz27DSIY0Qw',
    },
    {
        id: 'Audio7',
        subTitles: 'Santander mejores proveedores',
        title: 'Entrevistas',
        imgSrc: 'https://www.ludics.cl/demoweb/img/servicios/Audiovisual/7.- Foto video nuevo audiovisual_11zon.webp',
        videoSrc: 'https://www.ludics.cl/demoweb/img/servicios/Audiovisual/video/7-santander.mp4',
        videoUrl: 'https://www.youtube.com/watch?v=wb-El-W0S4k',
    },
    
];