export const EventoData = [
    {
        id: 'evento1',
        subTitles: 'PREMIO EXCELENCIA ACADÉMICA',
        title: 'EXPERIENCIAS CORPORATIVAS',
        imgSrc: 'https://www.ludics.cl/demoweb/img/servicios/Eventos/Santander 2024_11zon.webp',
        videoSrc: 'https://www.ludics.cl/demoweb/img/servicios/Eventos/video/1-excelencia.mp4',
        videoUrl: 'https://www.youtube.com/watch?v=xwSwJgxi3wM',
    },
    {
        id: 'evento2',
        subTitles: 'CONVENCIONES Y SEMINARIOS TEMÁTICOS',
        title: 'SUMMIT',
        imgSrc: 'https://www.ludics.cl/demoweb/img/servicios/Eventos/WOM (Summit y convenciones - Temáticos).webp',
        videoSrc: 'https://www.ludics.cl/demoweb/img/servicios/Eventos/video/2-tematicos.mp4',
        videoUrl: 'https://www.youtube.com/watch?v=rFyiU8ImRuQ',
    },
    {
        id: 'evento3',
        subTitles: 'LANZAMIENTOS DE PRODUCTOS',
        title: 'ACTIVACIONES DE MARCA',
        imgSrc: 'https://www.ludics.cl/demoweb/img/servicios/Eventos/LASER (Activación y lanzamiento de producto - Laser).webp',
        videoSrc: 'https://www.ludics.cl/demoweb/img/servicios/Eventos/video/3-laser.mp4',
        videoUrl: 'https://www.youtube.com/watch?v=MD7sbqtzn-c',
    },
    {
        id: 'evento4',
        subTitles: 'NAVIDADES Y CELEBRACIONES',
        title: 'TEMÁTICOS Y PERSONALIZADOS',
        imgSrc: 'https://www.ludics.cl/demoweb/img/servicios/Eventos/Navidad (Navidad Santander - Temáticos.webp',
        videoSrc: 'https://www.ludics.cl/demoweb/img/servicios/Eventos/video/4-navidadsantander.mp4',
        videoUrl: 'https://www.youtube.com/watch?v=3O8-VvJTiMQ',
    },
    {
        id: 'evento5',
        subTitles: 'THE BIG FONDA',
        title: 'FUERZA DIECIOCHERA',
        imgSrc: 'https://www.ludics.cl/demoweb/img/servicios/Eventos/WEBER (The big fonda - Fuerza deciochera).webp',
        videoSrc: 'https://www.ludics.cl/demoweb/img/servicios/Eventos/video/5-bigfonda.mp4',
        videoUrl: 'https://www.youtube.com/watch?v=Uc9VWtswDk4',
    },
    {
        id: 'evento6',
        subTitles: 'NOCHE DE JUEGOS',
        title: 'FORMATOS TELEVISIVOS',
        imgSrc: 'https://www.ludics.cl/demoweb/img/servicios/Eventos/NOCHE DE JUEGOS (Formato televisivo - Noche de juegos).webp',
        videoSrc: 'https://www.ludics.cl/demoweb/img/servicios/Eventos/video/6-noche-de-juegos.mp4',
        videoUrl: 'https://www.youtube.com/watch?v=opS1B-bmLiU',
    },
    {
        id: 'evento7',
        subTitles: 'TALLERES Y ACTIVIDADES PARA NIÑOS',
        title: 'KIDS DAY',
        imgSrc: 'https://www.ludics.cl/demoweb/img/servicios/Eventos/KIDS (Kids Day - Día de trabajo con hijos).webp',
        videoSrc: 'https://www.ludics.cl/demoweb/img/servicios/Eventos/video/7.-dia-trabajo-con-hijos.mp4',
        videoUrl: 'https://www.youtube.com/watch?v=CBhZEt63PVo',
    },
    {
        id: 'evento8',
        subTitles: 'CONTENIDO Y AMBIENTACIÓN PARA EVENTOS',
        title: 'FAMILY DAY',
        imgSrc: 'https://www.ludics.cl/demoweb/img/servicios/Eventos/familyday_11zon.webp',
        videoSrc: 'https://www.ludics.cl/demoweb/img/servicios/Eventos/video/8-family-day.mp4',
        videoUrl: 'https://www.youtube.com/watch?v=DgfMHB8j3r8',
    },
    {
        id: 'evento9',
        subTitles: 'ENTRETENCIÓN Y EXPERIENCIAS A TODOS LADOS',
        title: 'GIRAS',
        imgSrc: 'https://www.ludics.cl/demoweb/img/servicios/Eventos/GIRA (Beneficios Académicos - Gira).webp',
        videoSrc: 'https://www.ludics.cl/demoweb/img/servicios/Eventos/video/9-gira.mp4',
        videoUrl: 'https://www.youtube.com/watch?v=UOrpuHVbFXs',
    },
    {
        id: 'evento10',
        subTitles: 'ESTACIONES DE JUEGOS Y DESAFÍOS',
        title: 'ACTIVACIONES DE MARCA',
        imgSrc: 'https://www.ludics.cl/demoweb/img/servicios/Eventos/STAND (Estaciones y Desafios - STAND).webp',
        videoSrc: 'https://www.ludics.cl/demoweb/img/servicios/Eventos/video/corto-stand.mp4',
        videoUrl: 'https://www.youtube.com/watch?v=SpWaOGOo8yY',
    },
    
];