export const TeamBuildingData = [
    {
        id: 'team1',
        subTitles: 'Big Race',
        title: 'Formatos masivos',
        imgSrc: 'https://www.ludics.cl/demoweb/img/servicios/Team-Building/1- THE BIG RACE (Formato masivo - Big Race)_1_11zon.webp',
        videoSrc: 'https://www.ludics.cl/demoweb/img/servicios/Team-Building/video/1-big-race.mp4',
        videoUrl: 'https://www.youtube.com/watch?v=LTsj1Esy9R0',
    },
    {
        id: 'team2',
        subTitles: 'Actividad Outdoor',
        title: 'Desafíos en equipos',
        imgSrc: 'https://www.ludics.cl/demoweb/img/servicios/Team-Building/2- SOPROLE (Desafio en equipos - Outdoor)_2_11zon.webp',
        videoSrc: 'https://www.ludics.cl/demoweb/img/servicios/Team-Building/video/2-desafio-en-equipos.mp4',
        videoUrl: 'https://www.youtube.com/watch?v=xTEe1f1d3pY',
    },
    {
        id: 'team3',
        subTitles: 'Circuit challenge',
        title: 'Jornada de lideres',
        imgSrc: 'https://www.ludics.cl/demoweb/img/servicios/Team-Building/3- AFP MODELO (Circuit challenge - Jornada de lideres)_3_11zon.webp',
        videoSrc: 'https://www.ludics.cl/demoweb/img/servicios/Team-Building/video/3-jornada-lideres.mp4',
        videoUrl: 'https://www.youtube.com/watch?v=GTP01nkT914',
    },
    {
        id: 'team3.5',
        subTitles: 'pocket games',
        title: 'Formato televisivo',
        imgSrc: 'https://www.ludics.cl/demoweb/img/servicios/Team-Building/Poket.webp',
        videoSrc: 'https://www.ludics.cl/demoweb/img/servicios/Team-Building/video/corto-poket.mp4',
        videoUrl: 'https://www.youtube.com/watch?v=RN8Se6E0BQI',
    },
    {
        id: 'team4',
        subTitles: 'Mystery Box',
        title: 'Desafíos con sentido social',
        imgSrc: 'https://www.ludics.cl/demoweb/img/servicios/Team-Building/8- Mistery (Desafío con sentido - Mistery Box)_8.webp',
        videoSrc: 'https://www.ludics.cl/demoweb/img/servicios/Team-Building/video/8-desafios-con-sentido.mp4',
        videoUrl: 'https://www.youtube.com/watch?v=2O8p9DbEwnA',
    },
    {
        id: 'team5',
        subTitles: 'Actividad Indoor',
        title: 'Desafíos en equipos',
        imgSrc: 'https://www.ludics.cl/demoweb/img/servicios/Team-Building/4- DUOC UC (Desafío en equipos - Indoor)_4.webp',
        videoSrc: 'https://www.ludics.cl/demoweb/img/servicios/Team-Building/video/4-desafio-en-equipos-indoor.mp4',
        videoUrl: 'https://www.youtube.com/watch?v=GVAXJXJe4Uc',
    },
    {
        id: 'team6',
        subTitles: 'Actividad Outdoor',
        title: 'Jornada de integración',
        imgSrc: 'https://www.ludics.cl/demoweb/img/servicios/Team-Building/5- CYD (jornada de integración - Outdoor)_5.webp',
        videoSrc: 'https://www.ludics.cl/demoweb/img/servicios/Team-Building/video/5-jornada-de-integracion.mp4',
        videoUrl: 'https://www.youtube.com/watch?v=cOl3GXFr0Vc',
    },
    {
        id: 'team7',
        subTitles: 'Reality',
        title: 'game show TV',
        imgSrc: 'https://www.ludics.cl/demoweb/img/servicios/Team-Building/6- GAME SHOW (Game show - Indoor)_6_11zon.webp',
        videoSrc: 'https://www.ludics.cl/demoweb/img/servicios/Team-Building/video/6-game-show-monticello.mp4',
        videoUrl: 'https://www.youtube.com/watch?v=jJwz2_-cNk0',
    },
    {
        id: 'team8',
        subTitles: 'intervenciones',
        title: 'Recreo de oficina',
        imgSrc: 'https://www.ludics.cl/demoweb/img/servicios/Team-Building/7- Pocket (Formato Televisivo - Pocket Game)_7_11zon.webp',
        videoSrc: 'https://www.ludics.cl/demoweb/img/servicios/Team-Building/video/7-recreo-de-oficina.mp4',
        videoUrl: 'https://www.youtube.com/watch?v=vARoGkGyV-s',
    },
    {
        id: 'team9',
        subTitles: 'Desafíos corporativos',
        title: 'formato reality',
        imgSrc: 'https://www.ludics.cl/demoweb/img/servicios/Team-Building/9- DESAFIOS-EN-LAS-ALTURAS-(Desafíos Corporativos - Equipos en juego)_9.webp',
        videoSrc: 'https://www.ludics.cl/demoweb/img/servicios/Team-Building/video/9-equipos-en-juego.mp4',
        videoUrl: 'https://www.youtube.com/watch?v=LTafCLBq0b8',
    },
    
];